### ISSUE TITLE
issue with example

### ISSUE THREAD

**Issue by ret394** [ruby/rss#13]
files.
```
Gemfile
get-rss.rb
Gemfile.lock
```
see https://github.com/ruby/rss#consuming-rss

<details><summary>CLICK ME</summary>
<p>

```ruby
> ruby.exe .\get-rss.rb                                                   
./get-rss.rb:5: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Traceback (most recent call last):
        17: from ./get-rss.rb:5:in `<main>'
        16: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:19:in `open'
        15: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:50:in `open'
        14: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:744:in `open'
        13: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
        12: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
        11: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
        10: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
         9: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
         8: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:346:in `open_http'
         7: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
         3: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
         2: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `open'
C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `initialize': getaddrinfo: No such host is known.  (SocketError)
        17: from ./get-rss.rb:5:in `<main>'
        16: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:19:in `open'
        15: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:50:in `open'
        14: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:744:in `open'
        13: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
        12: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
        11: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
        10: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
         9: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
         8: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/open-uri.rb:346:in `open_http'
         7: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
         3: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
         2: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `open'
C:/Users/trip/Downloads/rubyinstaller-2.7.1-1-x64/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to www.ruby-lang.org:80 (getaddrinfo: No such host is known. ) (SocketError)
```

</p>
</details>

**Comment by kou** [comment]
> www.ruby-lang.org:80 (getaddrinfo: No such host is known. )

Do you have internet connection?

**Comment by ret394** [comment]
```ruby
  url = 'http://www.ruby-lang.org/en/feeds/news.rss'
  URI.open(url) do |rss|
    feed = RSS::Parser.parse(rss)
    puts "Title: #{feed.channel.title}"
    feed.items.each do |item|
      puts "Item: #{item.title}"
    end
  end
```
that was it.
