### ISSUE TITLE
Parsing the <pubDate> tag fails if it is in ISO8601 format

### ISSUE THREAD

**Issue by tkfu** [ruby/rss#6]
If the parser hits a date in ISO8601 format instead of RFC2822, it throws an error.

I understand that the RSS 2.0 spec says all date-times should conform to RFC2822, but it would be really nice if this gem could support ISO8601 as well, because Apple podcasts permits it. You can see this by parsing Apple's [example of a well-formed podcast feed](https://help.apple.com/itc/podcasts_connect/#/itcbaf351599). I saved that example as example.xml to test, and this is the result:

```
gem 'rss', '0.2.8'
require 'rss'
ex = open('example.xml')
feed = RSS::Parser.parse(ex)
```
Result:
```
Traceback (most recent call last):
       11: from /home/jon/.asdf/installs/ruby/2.5.1/bin/irb:11:in `<main>'
       10: from (irb):5
        9: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/parser.rb:88:in `parse'
        8: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/parser.rb:183:in `parse'
        7: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/rexmlparser.rb:18:in `_parse'
        6: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rexml/document.rb:242:in `parse_stream'
        5: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rexml/parsers/streamparser.rb:36:in `parse'
        4: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/parser.rb:377:in `tag_end'
        3: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/parser.rb:475:in `block in start_get_text_element'
        2: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/2.0.rb:82:in `pubDate='
        1: from /home/jon/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rss-0.2.8/lib/rss/2.0.rb:85:in `rescue in pubDate='
RSS::NotAvailableValueError (value <2019-05-16T07:00:00.000Z> of tag <pubDate> is not available.)
```

**Comment by kou** [comment]
You can accept ISO8601 format by disabling validation:

```ruby
gem 'rss', '0.2.8'
require 'rss'
ex = open('example.xml')
feed = RSS::Parser.parse(ex, :validate: false)
feed.items.each do |item|
  p item.pubDate
end
```

```text
2019-04-12 01:15:00 +0000
2019-06-06 12:00:00 +0000
2019-05-30 13:00:00 -0500
2019-05-23 02:00:00 -0700
2019-05-16 07:00:00 UTC
2019-05-10 01:15:00 +0000
2019-05-03 01:15:00 +0000
2019-04-26 01:15:00 +0000
2019-04-19 01:15:00 +0000
```

**Comment by tkfu** [comment]
Oh, that's perfect! Thanks!
